### ISSUE TITLE
Selection Art not Implement / nicht gebraucht?

### ISSUE THREAD

**Issue by FloThinksPi** [FloThinksPi/EA#1]
@TiMeJuMp Chris,Brauchen wir die SelectionArt überhaupt ? haben wir für die CSV ausgemacht , kann sie aber nicht im sourcecode finden.

**Comment by TiMeJuMp** [comment]
Na Maurice und Tobias haben zwei unterschiedliche SelectionArten zum implementieren. 

Deswegen wäre es schon sinnvoll, die Art mit zu Loggen?!

**Comment by TiMeJuMp** [comment]
Wann die das pushen musst du die morgen mal fragen.

**Comment by FloThinksPi** [comment]
Thx
